---
- name: Mount external storage drive
  hosts: all
  handlers:
    - import_tasks: ./handlers.yml
  tasks:
    - name: Update /etc/fstab
      become: yes
      lineinfile:
        dest: /etc/fstab
        line: '{{ item.line }}'
        state: '{{ item.state }}'
        create: yes
      with_items:
        - {
            line: 'UUID=a471b1cb-4573-4d09-bee0-21936d1bd7f3 /data ext4 nofail,x-systemd.device-timeout=10s 0 1',
            state: present,
          }
      notify:
        - restart system

    - name: Fix permissions
      become: yes
      file: path=/data owner=alarm group=alarm mode=0755 state=directory recurse=yes

    - name: Symlink to Downloads directory
      file:
        src: /data/Downloads
        dest: /home/alarm/Downloads
        owner: alarm
        group: alarm
        state: link
